'use client';

import { useEffect, useState } from 'react';

type Requisito = { id: string; tipo_cierre: string; nombre: string; codigo: string; modo: string; orden: number; activo: boolean };
type Causa = { id: string; codigo: string; nombre: string; orden: number; requiere_detalle: boolean; activo: boolean };

// Pantalla única para parametrizar qué exige cada tipo de cierre.
export default function CierresFunnelPage() {
  const [requisitos, setRequisitos] = useState<Requisito[]>([]); const [causas, setCausas] = useState<Causa[]>([]); const [msg, setMsg] = useState('');
  async function cargar() { const r = await fetch('/api/admin/funnel/cierres', { cache: 'no-store' }); const d = await r.json(); if (d.ok) { setRequisitos(d.requisitos); setCausas(d.causas); } }
  useEffect(() => { void cargar(); }, []);
  async function guardar(tipo: 'requisito' | 'causa', item: any, patch: any) { const r = await fetch('/api/admin/funnel/cierres', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tipo, id: item.id, ...patch }) }); const d = await r.json(); setMsg(d.ok ? 'Configuración guardada.' : d.error || 'No se pudo guardar.'); if (d.ok) void cargar(); }
  return <section className="space-y-6"><div><h1 className="text-2xl font-bold text-buscoedu-blue">Reglas de cierre</h1><p className="text-sm text-buscoedu-muted">Parametriza los requisitos de Ganada y Perdida sin cambiar código.</p></div>{msg && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</p>}<div className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Requisitos de cierre</h2><div className="space-y-2">{requisitos.map((r) => <div key={r.id} className="grid grid-cols-1 items-center gap-2 rounded-lg border p-3 md:grid-cols-[1fr_160px_100px]"><div><p className="font-medium">{r.nombre}</p><p className="text-xs text-gray-500">{r.tipo_cierre} · {r.codigo}</p></div><select value={r.modo} onChange={(e) => void guardar('requisito', r, { modo: e.target.value })} className="rounded border px-2 py-2 text-sm"><option value="obligatorio">Obligatorio</option><option value="opcional">Opcional</option><option value="no_utilizado">No utilizado</option></select><button onClick={() => void guardar('requisito', r, { activo: !r.activo })} className="rounded border px-2 py-2 text-xs">{r.activo ? 'Desactivar' : 'Activar'}</button></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Causas de Perdida</h2><div className="space-y-2">{causas.map((c) => <div key={c.id} className="grid grid-cols-1 items-center gap-2 rounded-lg border p-3 md:grid-cols-[1fr_180px_100px]"><div><p className="font-medium">{c.nombre}</p><p className="text-xs text-gray-500">Código: {c.codigo}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={c.requiere_detalle} onChange={(e) => void guardar('causa', c, { requiere_detalle: e.target.checked })} /> Requiere detalle</label><button onClick={() => void guardar('causa', c, { activo: !c.activo })} className="rounded border px-2 py-2 text-xs">{c.activo ? 'Desactivar' : 'Activar'}</button></div>)}</div></div></section>;
}
